<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Word;

class WordSeeder extends Seeder
{
    public function run(): void
    {
        $words = [
            // Easy words
            ['word' => 'ABOUT', 'difficulty' => 'easy'],
            ['word' => 'ABOVE', 'difficulty' => 'easy'],
            ['word' => 'AFTER', 'difficulty' => 'easy'],
            ['word' => 'AGAIN', 'difficulty' => 'easy'],
            ['word' => 'BRING', 'difficulty' => 'easy'],
            ['word' => 'CLOSE', 'difficulty' => 'easy'],
            ['word' => 'FIRST', 'difficulty' => 'easy'],
            ['word' => 'GREAT', 'difficulty' => 'easy'],
            ['word' => 'HOUSE', 'difficulty' => 'easy'],
            ['word' => 'LIGHT', 'difficulty' => 'easy'],
            ['word' => 'APPLE', 'difficulty' => 'easy'],
            ['word' => 'BREAD', 'difficulty' => 'easy'],
            ['word' => 'CHAIR', 'difficulty' => 'easy'],
            ['word' => 'DREAM', 'difficulty' => 'easy'],
            ['word' => 'EARTH', 'difficulty' => 'easy'],
            ['word' => 'FAITH', 'difficulty' => 'easy'],
            ['word' => 'GRASS', 'difficulty' => 'easy'],
            ['word' => 'HEART', 'difficulty' => 'easy'],
            ['word' => 'JUICE', 'difficulty' => 'easy'],
            ['word' => 'KNIFE', 'difficulty' => 'easy'],
            ['word' => 'LEMON', 'difficulty' => 'easy'],
            ['word' => 'MOUSE', 'difficulty' => 'easy'],
            ['word' => 'NURSE', 'difficulty' => 'easy'],
            ['word' => 'OCEAN', 'difficulty' => 'easy'],
            ['word' => 'PEACH', 'difficulty' => 'easy'],
            ['word' => 'QUIET', 'difficulty' => 'easy'],
            ['word' => 'RIVER', 'difficulty' => 'easy'],
            ['word' => 'SHEEP', 'difficulty' => 'easy'],
            ['word' => 'TABLE', 'difficulty' => 'easy'],
            ['word' => 'UNION', 'difficulty' => 'easy'],
            ['word' => 'VIRUS', 'difficulty' => 'easy'],
            ['word' => 'WATER', 'difficulty' => 'easy'],
            ['word' => 'YOUNG', 'difficulty' => 'easy'],
            ['word' => 'ZEBRA', 'difficulty' => 'easy'],

            // Medium words
            ['word' => 'FRAME', 'difficulty' => 'medium'],
            ['word' => 'PLANT', 'difficulty' => 'medium'],
            ['word' => 'QUEST', 'difficulty' => 'medium'],
            ['word' => 'ROYAL', 'difficulty' => 'medium'],
            ['word' => 'SMILE', 'difficulty' => 'medium'],
            ['word' => 'TRAIN', 'difficulty' => 'medium'],
            ['word' => 'VOICE', 'difficulty' => 'medium'],
            ['word' => 'WORTH', 'difficulty' => 'medium'],
            ['word' => 'YOUTH', 'difficulty' => 'medium'],
            ['word' => 'BEACH', 'difficulty' => 'medium'],
            ['word' => 'BLEND', 'difficulty' => 'medium'],
            ['word' => 'CRISP', 'difficulty' => 'medium'],
            ['word' => 'DRIVE', 'difficulty' => 'medium'],
            ['word' => 'EAGER', 'difficulty' => 'medium'],
            ['word' => 'FLOCK', 'difficulty' => 'medium'],
            ['word' => 'GLASS', 'difficulty' => 'medium'],
            ['word' => 'HONEY', 'difficulty' => 'medium'],
            ['word' => 'INDEX', 'difficulty' => 'medium'],
            ['word' => 'JELLY', 'difficulty' => 'medium'],
            ['word' => 'KNACK', 'difficulty' => 'medium'],
            ['word' => 'LUNCH', 'difficulty' => 'medium'],
            ['word' => 'MERCY', 'difficulty' => 'medium'],
            ['word' => 'NOBLE', 'difficulty' => 'medium'],
            ['word' => 'OPERA', 'difficulty' => 'medium'],
            ['word' => 'PRIZE', 'difficulty' => 'medium'],
            ['word' => 'QUILT', 'difficulty' => 'medium'],
            ['word' => 'RANCH', 'difficulty' => 'medium'],
            ['word' => 'SHINE', 'difficulty' => 'medium'],
            ['word' => 'THUMB', 'difficulty' => 'medium'],
            ['word' => 'URBAN', 'difficulty' => 'medium'],
            ['word' => 'VIVID', 'difficulty' => 'medium'],
            ['word' => 'WORST', 'difficulty' => 'medium'],
            ['word' => 'YEAST', 'difficulty' => 'medium'],
            ['word' => 'ZONED', 'difficulty' => 'medium'],

            // Hard words
            ['word' => 'CYNIC', 'difficulty' => 'hard'],
            ['word' => 'EPOXY', 'difficulty' => 'hard'],
            ['word' => 'FJORD', 'difficulty' => 'hard'],
            ['word' => 'GLYPH', 'difficulty' => 'hard'],
            ['word' => 'LYMPH', 'difficulty' => 'hard'],
            ['word' => 'NYMPH', 'difficulty' => 'hard'],
            ['word' => 'PROXY', 'difficulty' => 'hard'],
            ['word' => 'QUIRK', 'difficulty' => 'hard'],
            ['word' => 'WALTZ', 'difficulty' => 'hard'],
            ['word' => 'ZESTY', 'difficulty' => 'hard'],
            ['word' => 'ABYSS', 'difficulty' => 'hard'],
            ['word' => 'BAYOU', 'difficulty' => 'hard'],
            ['word' => 'CRYPT', 'difficulty' => 'hard'],
            ['word' => 'DWARF', 'difficulty' => 'hard'],
            ['word' => 'ENVOY', 'difficulty' => 'hard'],
            ['word' => 'FICUS', 'difficulty' => 'hard'],
            ['word' => 'GAUZE', 'difficulty' => 'hard'],
            ['word' => 'HAZEL', 'difficulty' => 'hard'],
            ['word' => 'IVORY', 'difficulty' => 'hard'],
            ['word' => 'JUMBO', 'difficulty' => 'hard'],
            ['word' => 'KAYAK', 'difficulty' => 'hard'],
            ['word' => 'LARVA', 'difficulty' => 'hard'],
            ['word' => 'MUMMY', 'difficulty' => 'hard'],
            ['word' => 'NINJA', 'difficulty' => 'hard'],
            ['word' => 'OZONE', 'difficulty' => 'hard'],
            ['word' => 'PIXEL', 'difficulty' => 'hard'],
            ['word' => 'QUASH', 'difficulty' => 'hard'],
            ['word' => 'RHINO', 'difficulty' => 'hard'],
            ['word' => 'SQUAD', 'difficulty' => 'hard'],
            ['word' => 'TWIRL', 'difficulty' => 'hard'],
            ['word' => 'VIXEN', 'difficulty' => 'hard'],
            ['word' => 'WHARF', 'difficulty' => 'hard'],
            ['word' => 'YACHT', 'difficulty' => 'hard'],
            ['word' => 'ZONAL', 'difficulty' => 'hard'],
        ];

        foreach ($words as $wordData) {
            Word::create($wordData);
        }
    }
}
